import os
import random
from dotenv import load_dotenv
import discord
from discord import client
from discord.ext import commands

def RandomUrl():
    url = [
        "http://alien-ufo-research.com/reptilians/",
        "https://www.flightradar24.com/",
        "http://nooooooooooooooo.com/",
        "http://secrettechnology.com/",
        "http://www.patience-is-a-virtue.org/",
        "https://isitchristmas.com/",
        "http://omfgdogs.com/",
        "http://zombo.com/",
        "http://www.rainymood.com/",
        "http://www.fallingfalling.com/",
        "http://corgiorgy.com/",
        "http://www.pointerpointer.com/",
        "http://eelslap.com/",
        "http://zoomquilt.org/",
        "http://beesbeesbees.com/",
        "http://www.thepictureofeverything.com/",
        "http://doughnutkitten.com/",
        "https://www.futureme.org/",
        "http://www.newyearexercise.com/",
        "https://web.archive.org/web/20180201230730/http://www.dragomirsdiary.com/2011/08/hello-diary.html",
        "http://5secondfilms.com/",
        "http://alpha61.com/primenumbershittingbear/",
        "http://www.myhousematesdiary.com/",
        "http://www.cachemonet.com/",
        "http://clickingbad.nullism.com/",
        "http://www.gizoogle.net/",
        "https://ncase.me/trust/",
        "http://www.clicktoremove.com/",
        "http://vectorpark.com/head/",
        "https://www.purristan.com/",
        "https://www.airfrais.eu/us/index.html",
        "http://www.nobodyhere.com/justme/me.here",
        "http://www.superbad.com/",
        "http://therevolvinginternet.com/",
        "http://get.your-d.tk/",
        "http://www.miserablebastard.com/",
        "http://www.freechocolate.com/",
        "https://morelessgame.com/",
        "http://sheepfilms.co.uk/category/shortfilms/",
        "http://strangehorizons.com/non-fiction/articles/installing-linux-on-a-dead-badger-users-notes/",
        "http://perfectlytimedphotos.com/popular/perfectly-timed-photo",
        "http://jpriest.com/gamez/pinguxtreme.swf",
        "http://www.bradthegame.com/",
        "http://theworstthingsforsale.com/",
        "https://s3.mirror.co.uk/click-the-colour-and-not-the-word/index.html",
        "http://theoatmeal.com/comics/dog_paradox",
        "http://www.catbirdseat.org/catbirdseat/bingo.html",
        "http://unomoralez.com/",
        "http://www.fincher.org/Misc/Pennies/BigTower.shtml",
        "http://www.cleverbot.com/",
        "http://www.hat.net/abs/noclick/index.html",
        "http://www.staggeringbeauty.com/",
        "http://burymewithmymoney.com/",
        "http://just-shower-thoughts.tumblr.com/",
        "http://www.trypap.com/",
        "http://www.republiquedesmangues.fr/",
        "http://www.koalastothemax.com/",
        "http://www.carrotmuseum.co.uk/carrotcolours.html",
        "http://grandpanoclothes.com/",
        "http://www.everydayim.com/",
        "http://hasthelargehadroncolliderdestroyedtheworldyet.com/",
        "http://ninjaflex.com/",
        "http://chrismckenzie.com/",
        "http://corndogoncorndog.com/",
        "http://gameaboutsquares.com/",
        "https://ncase.me/trust/",
        "http://salmonofcapistrano.com/",
        "http://www.wutdafuk.com/",
        "http://www.ouaismaisbon.ch/",
        "http://unicodesnowmanforyou.com/",
        "http://www.psyhigh.com/",
        "http://www.internetisshit.org/",
        "http://www.fmylife.com/",
        "http://www.realultimatepower.net/index4.htm",
        "http://rulesoftheinternet.com/index.php?title=Main_Page",
        "http://www.markdalderup.com/daylight-of-darkness/the-start-of-the-world/",
        "http://presidentialpickuplines.tumblr.com/",
        "http://sarina-brewer.com/",
        "http://chickswithstevebuscemeyes.tumblr.com/",
        "http://thingsididlastnight.com/",
        "http://www.heptune.com/farts.html",
        "http://inventorspot.com/articles/body_bread_13546",
        "http://memebase.cheezburger.com/pictureisunrelated",
        "http://alien-ufo-research.com/news/2013/proof-of-time-travelers.php",
        "http://pixelsfighting.com/",
        "http://hardcoreprawnlawn.com/",
        "http://www.slightlyinteresting.com/lavalamp/lava.asp",
        "http://thefo.nz/",
        "http://faceofdisapproval.com/",
        "http://semanticresponsiveillustration.com/",
        "http://dogs.are.the.most.moe/",
        "https://web.archive.org/web/20190512120348/https://oct82.com/",
        "http://www.drawastickman.com",
        "https://trek.nasa.gov/mars/index.html",
        "http://ihumans.tumblr.com/",
        "http://whos.agood.dog/lesser.dog/",
        "http://chatwithhodor.com/",
        "https://web.archive.org/web/20170514160422/http://manbabies.com/",
        "http://www.rinkworks.com/bookaminute/classics.shtml",
        "http://www.ijustwantyourmoney.com/",
        "http://www.onemilliongiraffes.com/",
        "http://www.lkozma.net/wpv/index.html",
        "http://www.fieggen.com/shoelace/index.htm",
        "http://playing.hypernom.com/monkeys",
        "http://www.sam-i-am.com/play/5k/expletives/index.html",
        "http://beaarthurmountainspizza.tumblr.com/",
        "http://www.stopabductions.com/",
        "https://swatblog.rtgp.xyz/",
        "http://kimjongillookingatthings.tumblr.com/",
        "http://garfieldminusgarfield.net/",
        "http://dogeweather.com/",
        "http://www.hen2hen.com/",
        "https://web.archive.org/web/20160725231633/http://celebritiesaskids.net/",
        "http://codepen.io/ge1doot/full/WbWQOP/",
        "http://icanhas.cheezburger.com/",
        "http://www.engrish.com/",
        "http://www.astrohamster.com/",
        "http://stuffonmycat.com/",
        "http://www.bbc.com/future/bespoke/story/20150306-journey-to-the-centre-of-earth/index.html",
        "http://www.cowsgomoo.co.uk/",
        "http://www.woot.co.uk/",
        "https://bouncingdvdlogo.com/",
        "http://orteil.dashnet.org/cookieclicker/",
        "http://themostseconds.com/",
        "http://www.midwaymeetup.com/",
        "https://www.youtube.com/watch?v=9C_HReR_McQ&feature=emb_logo",
        "http://www.handspeak.com/word/",
        "http://topdocumentaryfilms.com/",
        "http://www.madsci.org/cgi-bin/lynn/jardin/SCG",
        "http://trumpdonald.org/",
        "https://drawception.com",
        "http://badkidsjokes.tumblr.com/",
        "http://internet-map.net/",
        "https://youtu.be/9C_HReR_McQ",
        "http://hyperboleandahalf.blogspot.co.uk/",
        "http://slither.io/",
        "http://www.youareinaforest.com/",
        "http://remoji.com/",
        "http://shiiiit.com/",
        "http://www.howmanypeopleareinspacerightnow.com/",
        "http://hmpg.net/",
        "http://conceptlab.com/simulator/morning/clock800.html",
        "https://www.kamogo.com/9",
        "http://www.therestartpage.com/",
        "http://www.stinkymeat.net/",
        "http://www.eviloverlord.com/lists/overlord.html",
        "http://www.windows93.net/",
        "http://thefuckingtime.com/",
        "http://make-everything-ok.com/",
        "http://what-if.xkcd.com/8/",
        "http://www.danielyeow.com/2011/drawing-molecules/",
        "http://inventorspot.com/articles/ten_bizarre_japanese_soft_drinks_5225",
        "http://www.wikihow.com/Recycle-Your-Socks",
        "https://www.dctech.com/physics/notes/0005.php",
        "http://www.pintprice.com/",
        "http://www.barefooters.org/",
        "http://www.weirdconverter.com/",
        "http://www.theflatearthsociety.org/cms/",
        "http://scienceblogs.com/goodmath/2006/10/12/who-needs-a-calculator-multipl/",
        "http://www.coincalc.com/",
        "http://festivusweb.com/",
        "http://www.appropedia.org/Solar_Charged_Lawnmower",
        "http://www.genderanalyzer.com/",
        "http://www.muppetlabs.com/~breadbox/txt/al.html",
        "http://fliptitle.com/",
        "http://www.worldbeardchampionships.com/photos/",
        "http://www.fishcam.com/",
        "http://www.ehow.com/how_4594591_suck-egg-bottle.html",
        "https://www.youtube.com/watch?v=jU9USxJ9vPs",
        "http://www.venganza.org/",
        "http://www.humanforsale.com/",
        "http://www.willitblend.com/",
        "http://www.icbe.org/",
        "http://www.museumofconceptualart.com/accomplished/index.html",
        "https://scatter.wordpress.com/2010/05/30/the-shortest-possible-game-of-monopoly-21-seconds/",
        "http://www.thesmokinggun.com/time-waster",
        "https://www.youtube.com/askaninja",
        "http://www.godecookery.com/mythical/mythical.htm",
        "http://www.sandalandsoxer.co.uk/home.htm",
        "http://www.lileks.com/oldads/index.html",
        "http://australianmuseum.net.au/death-the-last-taboo",
        "http://www.shadyurl.com/",
        "http://memebase.cheezburger.com/thisisphotobomb",
        "https://www.gutenberg.org/",
        "http://ipetcompanion.com",
        "http://findtheinvisiblecow.com/",
        "https://web.archive.org/web/20190618062455/http://www.iloveyoulikeafatladylovesapples.com/",
        "http://www.thepointless.com/reddot",
        "http://www.rrrather.com/",
        "http://virtualpiano.net/",
        "http://drunkenme.com/movie-drinking-games/",
        "http://findagrave.com/",
        "https://onetinyhand.com/",
        "http://zoomquilt.org/",
        "http://cachemonet.com/",
        "http://www.plspetdoge.com/",
        "http://salmonofcapistrano.com/",
        "http://www.firstmenonthemoon.com/",
        "http://codepen.io/akm2/full/rHIsa",
        "https://www.housecreep.com/",
        "http://you.regettingold.com/",
        "http://hotdogcat.com/",
        "http://instantrimshot.com/",
        "http://www.anothersadtrombone.com/",
        "https://web.archive.org/web/20180211011023/http://cutecatnames.com/",
        "http://www.instantwhoop.com",
        "http://drunkenme.com/movie-drinking-games/",
        "https://longdogechallenge.com/",
        "http://heeeeeeeey.com/",
        "http://corndog.io/",
        "https://mondrianandme.com/",
        "https://puginarug.com",
        "https://alwaysjudgeabookbyitscover.com",
        "https://thatsthefinger.com/",
        "https://cant-not-tweet-this.com/",
        "http://eelslap.com/",
        "http://www.staggeringbeauty.com/",
        "http://burymewithmymoney.com/",
        "https://smashthewalls.com/",
        "https://jacksonpollock.org/",
        "http://endless.horse/",
        "https://www.trypap.com/",
        "http://www.republiquedesmangues.fr/",
        "http://www.movenowthinklater.com/",
        "http://www.partridgegetslucky.com/",
        "http://www.rrrgggbbb.com/",
        "http://beesbeesbees.com/",
        "http://www.koalastothemax.com/",
        "http://www.everydayim.com/",
        "http://randomcolour.com/",
        "http://cat-bounce.com/",
        "http://chrismckenzie.com/",
        "https://thezen.zone/",
        "http://hasthelargehadroncolliderdestroyedtheworldyet.com/",
        "http://ninjaflex.com/",
        "http://ihasabucket.com/",
        "http://corndogoncorndog.com/",
        "http://www.hackertyper.com/",
        "https://pointerpointer.com",
        "http://imaninja.com/",
        "http://drawing.garden/",
        "http://www.ismycomputeron.com/",
        "http://www.nullingthevoid.com/",
        "http://www.muchbetterthanthis.com/",
        "http://www.yesnoif.com/",
        "http://lacquerlacquer.com",
        "http://potatoortomato.com/",
        "http://iamawesome.com/",
        "https://strobe.cool/",
        "http://www.pleaselike.com/",
        "http://crouton.net/",
        "http://corgiorgy.com/",
        "http://www.wutdafuk.com/",
        "http://unicodesnowmanforyou.com/",
        "http://chillestmonkey.com/",
        "http://scroll-o-meter.club/",
        "http://www.crossdivisions.com/",
        "http://tencents.info/",
        "https://boringboringboring.com/",
        "http://www.patience-is-a-virtue.org/",
        "http://pixelsfighting.com/",
        "http://isitwhite.com/",
        "https://existentialcrisis.com/",
        "http://onemillionlols.com/",
        "http://www.omfgdogs.com/",
        "http://oct82.com/",
        "http://chihuahuaspin.com/",
        "http://www.blankwindows.com/",
        "http://dogs.are.the.most.moe/",
        "http://tunnelsnakes.com/",
        "http://www.trashloop.com/",
        "http://www.ascii-middle-finger.com/",
        "http://spaceis.cool/",
        "http://www.donothingfor2minutes.com/",
        "http://buildshruggie.com/",
        "http://buzzybuzz.biz/",
        "http://yeahlemons.com/",
        "http://wowenwilsonquiz.com",
        "https://thepigeon.org/",
        "http://notdayoftheweek.com/",
        "http://www.amialright.com/",
        "http://nooooooooooooooo.com/",
        "https://greatbignothing.com/",
        "https://zoomquilt.org/",
        "https://dadlaughbutton.com/",
        "https://www.bouncingdvdlogo.com/",
        "https://remoji.com/",
        "http://papertoilet.com/",
        "https://loopedforinfinity.com/",
    ]

    return random.choice(url)

def RandomTopic():
    topic = [
        "Why doesn't glue stick to the bottle?",
        "Can you play chess?",
        "Have you ever invented a fairly unique meal or drink?",
        "What is squirting? Can any woman do it?",
        "Are there any sexual acts that make you uncomfortable?",
        "When you open a bag of cotton balls, is the top one meant to be thrown away?",
        "What turns you on almost instantly?",
        "If you knew you had only 2 weeks to live and death was imminent what ae the regrets you would have?",
        "What do you think your worst facial feature?",
        "What gets you angry?",
        "How come lemon washing up liquid contains real lemons, but lemon juice contains artificial flavorings.",
        "What is the longest plane trip you have taken?",
        "Do you believe in evolution or religion?",
        "Who was the first person to bring up the idea of marriage: you or your wife?",
        "Do You Have Any Major Medical Conditions I Should Know About?",
        "Where would your wife say you had your first date?",
        "If you could change something about yourself, what would it be & why?",
        "Why does caregiver and caretaker mean the same thing?",
        "Why does your gynecologist leave the room when you undress?",
        "Are you psychic in any way?",
        "If people with one arm go to get their nails done, do they pay half price?",
        "Vaccines",
        "Can you share with me some of the current events in this week in the world?",
        "Do you own a house?",
        "What ingredient in fresh milk is eventually devoured by bacteria, causing the sour taste? Lactose.",
        "Do you dream often?",
        "Ever Get So Drunk You Don't Remember The Entire Night?",
        "Pottery",
        "Why is snow white and ice clear? Aren't they just different forms of water?",
        "Do you have any siblings?",
        "Why do toasters always have a setting that burns the toast to a horrible crisp which no decent human being "
        "would eat?",
        "Do you like winter time or spring time? Why?",
        "Bright room or dark room?",
        "May Queen, Wisley Crab, Foxwhelps and Lane's Prince Albert are all species of what? Apples.",
        "How high can you jump?",
        "Best Vacation?",
        "Do You Think Our President Is A Good President?",
        "What place in the US would you most like to visit? Why?",
        "Where did you go for dinner after the marriage?",
        "Betty Joan Perske changed her name to what? Lauren Bacall",
        "Isn't Disney World just a people's trap operated by a mouse?",
        "Can a heterosexual male ever wear pink?",
        "What was the best thing about your old school?",
        "Do You Have A Role Model?",
        "Have You Ever Been Part Of A Not-For-Profit Organization And Done Volunteer Work?",
        "Ever Lost A Pet?",
        "If someone has a mid-life crisis while playing hide and seek, does he automatically lose because he can't "
        "find himself?",
        "Call me radical, but why can't we talk on elevators again?",
        "Would you ever go on Big Brother?",
        "Do you use an umbrella when it rains?",
        "Have You Ever Been To A School Or College Reunion?",
        "Do you like it when I take control in bed, or do you like being in control?",
        "Which is your favourite ice cream, junk food and dessert?",
        "What is the silliest recent fashion trend?",
        "What's your idea of foreplay?",
        "What's your idea of good foreplay?",
        "Which Disney princess do you find to be the most attractive?",
        "Who around you has the worst luck?",
        "What if Batman gets bitten by a vampire?",
        "What's your favourite city beginning with the letter Y?",
        "What percentage of the house work would your spouse say they do?",
        "If swimming is good for your shape, then why do the whales look the way they do?",
        "Pigs",
        "Do you think you're a good judge of character?",
        "Do you like vanilla or chocolate?",
        "What problems will technology solve in the next 5 years? What problems will it create?",
        "What fashion trend do you wish would come back?",
        "Who is the better cook?",
        "What is your favorite activity and why?",
        "What is your spouse's favorite candy bar?",
        "If the temperature is zero outside today and it's going to be twice as cold tomorrow, how cold will it be?",
        "Have you ever won a prize in a contest?",
        "How much time should couples spend together?",
        "OK, so what's the speed of dark?",
        "What nation's military attached dynamite packs to Dobermans before sending them into Palestinian guerrilla "
        "hideouts? Israel.",
        "What would you do if your husband hired a beautiful secretary?",
        "Do you have any contraction of diseases?",
        "What's the furthest you've ever been on holiday?",
        "What song would you pick to describe your spouse in the bedroom?",
        "Do hungry crows have ravenous appetites?",
        "Do you miss anyone?",
        "Would you rather be the fella in a movie who gets the girl or the baddie with all the good lines?",
        "Where do you think your wife would put a handful of itching powder?",
        "If you were a car, what kind of car would you be?",
        "When is your mother-in-law's birthday?",
        "Have you ever been in a submarine?",
        "Would you rather love and not be loved back, or be loved but never love?",
        "If you invented a monster what would you call it?",
        "What's your least favourite personality trait you like about yourself?",
        "How long did you last phone call last?",
        "Do you need to know everything about someone抯 past?",
        "If a lesbian has sex with other women but never with another man is she still considered a virgin?",
        "Describe your spouse's sexiest Pajamas.",
        "What person, character, or sound does The Groom best do an impersonation of?",
        "What are your nicknames?",
        "Can bald men get lice?",
        "What would your spouse request as a last meal?",
        "Are you a good actor?",
        "How many cousins does your spouse have?",
        "Who would win in a fight? Chuck Norris or Jack Bauer?",
    ]

    return random.choice(topic)

def gen_embed(title, url, description, color):
    return discord.Embed(title = title, url = url, description = description, color = color)

load_dotenv()
client = commands.Bot(command_prefix = os.environ["PREFIX"])

@client.event
async def on_ready():
    print(f"Bot `{client.user}` with id `{client.user.id}` is ready")

@client.event
async def on_message(message):
    if message.content == os.environ["PREFIX"] + "website":
        url = RandomUrl()
        await message.channel.send(embed = gen_embed("Take this website!", "", f"**{ url }**", 0xFF5733))

    if message.content == os.environ["PREFIX"] + "topic":
        await message.channel.send(RandomTopic())

client.run(os.environ["TOKEN"])
